version: '3.7'

services:
  toy:
    image: nginx
    volumes:
      - ./storage:/storage:Z
      - ./nginx/log:/var/log/nginx:Z
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro,Z
    ports:
      - 7070:80